title: "ARSC 5040 Qualitative Data Tools"
author: "Jordan Wrigley and Nickoal Eichmann-Kalwara"
description: "University of Colorado Boulder"
permalink: /home.md/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false       # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: true            # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Home", file: "home.md", icon: none}
  - {title: "Course Schedule", file: "modules.md", icon: none}
  - {title: "Final Project", file: "finalproject.md", icon: none}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Email Us, icon: envelope, url: "mailto:nickoal.eichmann@colorado.edu;jordan.wrigley@colorado.edu"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
